services:
  mongo-car:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_car_data:/data/db

  mysql-carRepair:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql_carRepair_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=abc123
  
  mysql-mechanic:
    image: mysql:latest
    ports:
      -3307:3306
    volumes:
      - mysql_mechanic_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=abc123

car-service:
  depends_on:
    - mongo-car
  image: robbie013123/car-service
  ports: 
    - 8080:8080
  links:
    - mongo-car
  environment:
    MONGODB_PORT: 27017
    MONGODB_HOST: mongo-car

mechanic-service:
  depends_on:
    - mysql_mechanic
  image: robbie013123/mechanic-service
  ports:
    - 8082:8082
  links:
    - mysql-mechanic
  environment:
    MYSQL_DB_USERNAME: root
    MYSQL_DB_PASSWORD: abc123
    MYSQL_DB_HOST: mysql-mechanic
    MYSQL_DB_PORT: 3307

carRepair-service:
  depends_on:
    - car-service
    - mechanic-service
  image: robbie013123/carRepair-service
  ports:
    - 8081:8081
  links:
    - car-service
    - mechanic-service
  environment:
    CAR_SERVICE_BASEURL: car-service:8080
    MECHANIC_INFO_SERVICE_BASEURL: mechanic-service:8082
    MYSQL_DB_USERNAME: root
    MYSQL_DB_PASSWORD: abc123
    MYSQL_DB_HOST: mysql-carRepair
    MYSQL_DB_PORT: 3306

  api-gateway:
    depends_on:
      - car-service
      - carRepair-service
    image: robbie013123/ede-api-gateway
    ports:
      - 8083:8083
    links:
      - car-service
      - carRepair-service
    environment:
      CAR_SERVICE_BASEURL: car-service:8080
      CARREPAIR_SERVICE_BASEURL: carRepair-service:8081

volumes:
  mongodb_car_data:
  mysql_carRepair_data:
  mysql_mechanic_data: